### ISSUE TITLE
Release 2.3.7 has fragile six dependency

### ISSUE THREAD

**Issue by ThrawnCA** [mcmtroffaes/pathlib2#81]
The new 2.3.7 release depends on `six.moves.collections_abc`, which was introduced in `six` 1.13.0, but `setup.py` does not specify that that the `six` dependency must be `>=1.13.0`. This can result in failures if projects depend on `pathlib2` without manually specifying a newer `six` version themselves.

**Comment by ThrawnCA** [comment]
Suggested fix is to update `setup.py` from `install_requires=['six'],` to `install_requires=['six>=1.13.0'],`

**Comment by maniakjaniak** [comment]
+1 for this issue. We can no longer deploy as a result. 

Error:
```

[2022-02-09T00:37:02Z]   File "/var/lib/buildkite-agent/.local/lib/python2.7/site-packages/pathlib2/__init__.py", line 26, in <module>
--
  | [2022-02-09T00:37:02Z]     from six.moves.collections_abc import Sequence
  | [2022-02-09T00:37:02Z] ImportError: No module named collections_abc

```

**Comment by maniakjaniak** [comment]
Can someone please reply to this issue? I'm really not sure what I can do atm. This has prevented all buildkite builds in deploying. 

Our project specifies six version 1.16.0 and still fails on the import path.

Looks like you don't support Python 2.7 anymore - I'll move our deployment to 3+ and go from there.

**Comment by julian-huff** [comment]
We were having this issue when using `virtualenv`.

Updating
```
pip install virtualenv
```
to
```
pip install virtualenv pathlib2==2.3.6
```

in our build system resolved our issue for now.

**Comment by alexk307** [comment]
This also broke my build system as well, due to a long dependency chain that ended in pulling the latest release `2.3.7-post0`.

What I don't understand is why there are updates to a back ported Python 2 library being pushed, when the description of the README states `As of January 1 2020, this repository will no longer receive any further feature updates, as Python 2 is no longer supported`. On 1/1/2020, the released version was `2.3.5`, since then there have been [87 commits](https://pypi.org/project/pathlib2/#history), with two releases coming back to back in the past few days.

**Comment by mcmtroffaes** [comment]
I released 2.3.7-post0 a few hours after the original release to mitigate this problem; see #80. Isn't pip picking it up?

**Comment by alexk307** [comment]
Pip picks up the new release just fine, but the `-post0` release does not fix the issue for some people.

https://github.com/jazzband/pathlib2/compare/2.3.7...2.3.7-post0#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R44

` install_requires=['six>=1.13.0'],` is still higher than it was before and can easily conflict with other dependencies that need `six` too. In this case, it should have been tied down to the last version of `six`that this works for, not `six>=1.13.0`, but something like `six<=last.version.working`

**Comment by mcmtroffaes** [comment]
```
$ pip install pathlib2
Collecting pathlib2
  Downloading pathlib2-2.3.7.post0-py2.py3-none-any.whl (18 kB)
Collecting six>=1.13.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, pathlib2
Successfully installed pathlib2-2.3.7.post0 six-1.16.0
```

Looks fixed to me. Let me know if there's still a problem.

If you need older versions of six, then use an older version of pathlib2.

**Comment by alexk307** [comment]
> If you need older versions of six, then use an older version of pathlib2.

You do realize that `virtualenv` has a floating dep to this library, right? https://github.com/pypa/virtualenv/blob/f7ababdf0be4db3625444bbb20fa268a3885e645/setup.cfg#L49

You can't just tie it down to an older version, it's going to pull the latest.

**Comment by mcmtroffaes** [comment]
```
$ pip install pathlib2 six==1.10.0
Collecting pathlib2
  Using cached pathlib2-2.3.7.post0-py2.py3-none-any.whl (18 kB)
Collecting six==1.10.0
  Using cached six-1.10.0-py2.py3-none-any.whl (10 kB)
Collecting pathlib2
  Downloading pathlib2-2.3.6-py2.py3-none-any.whl (17 kB)
Installing collected packages: six, pathlib2
Successfully installed pathlib2-2.3.6 six-1.10.0
```

As you can see, pip pulls in 2.3.6 as expected - this looks good to me. If you still get errors, please tell me exactly how to reproduce, and I'll look into it. However, as far as I can tell, all is fixed.

**Comment by ghmj2417** [comment]
It's about installing `virtualenv` which has a dependency on `pathlib2`.  I don't know if other individuals are experiencing something similar but when six is already installed that is <1.13, example in my case 1.9, and install `virtualenv` I get the following output from the pip install of virtualenv for Python 2.7:
```
[user]# pip install virtualenv
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: https://pypi.org/api/pypi/inin-pypi/simple, https://pypi.org/api/pypi/pypi/simple
Collecting virtualenv
  Downloading https://pypi.org/api/pypi/pypi/packages/packages/99/0c/26206e19ab4176532dc0509e67e4d0cc8e6a82eab204e7e4ceff2664769a/virtualenv-20.13.1-py2.py3-none-any.whl (8.6 MB)
     |████████████████████████████████| 8.6 MB 52.3 MB/s
Requirement already satisfied: six<2,>=1.9.0 in /usr/lib/python2.7/site-packages (from virtualenv) (1.9.0)
Requirement already satisfied: filelock<4,>=3.2 in /usr/lib/python2.7/site-packages (from virtualenv) (3.2.1)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /usr/lib/python2.7/site-packages (from virtualenv) (2.1.3)
Requirement already satisfied: platformdirs<3,>=2 in /usr/lib/python2.7/site-packages (from virtualenv) (2.0.2)
Collecting pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"
  Downloading https://pypi.org/api/pypi/pypi/packages/packages/59/b7/6cb6e5cb66d934b9f3d51761ceb4a52bcdd4446048b9107e7ebb60b8a04c/pathlib2-2.3.7.post0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: distlib<1,>=0.3.1 in /usr/lib/python2.7/site-packages (from virtualenv) (0.3.4)
Requirement already satisfied: importlib-resources>=1.0; python_version < "3.7" in /usr/lib/python2.7/site-packages (from virtualenv) (3.3.1)
Requirement already satisfied: contextlib2; python_version < "3" in /usr/lib/python2.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->virtualenv) (0.6.0.post1)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python2.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->virtualenv) (1.2.0)
Requirement already satisfied: configparser>=3.5; python_version < "3" in /usr/lib/python2.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->virtualenv) (4.0.2)
Requirement already satisfied: typing; python_version < "3.5" in /usr/lib/python2.7/site-packages (from pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"->virtualenv) (3.10.0.0)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/lib64/python2.7/site-packages (from pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"->virtualenv) (1.10.0)
Requirement already satisfied: singledispatch; python_version < "3.4" in /usr/lib/python2.7/site-packages (from importlib-resources>=1.0; python_version < "3.7"->virtualenv) (3.7.0)
Installing collected packages: pathlib2, virtualenv
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
pathlib2 2.3.7.post0 requires six>=1.13.0, but you'll have six 1.9.0 which is incompatible.
Successfully installed pathlib2-2.3.7.post0 virtualenv-20.13.1
```
As you can see pip will install the latest version of pathlib2.  Now I get it, the arguments can be said to look at the error and upgrade six to >= 1.13.0.  Just keep in mind, not everyone can do that.

**Comment by mcmtroffaes** [comment]
Thanks @Ok, I got this reproduced.

**Comment by mcmtroffaes** [comment]
Many thanks @ghmj2417 for carefully explaining. I now have this fully reproduced by running ``pip install pathlib2 six==1.10.0`` on an old python 2 pip. There's all sorts of things that could be done, but I think the very simplest thing to do is simply to yank 2.3.7-post0 (some small bug fixes might be missing as a result, but at this point I don't think anyone really cares?). I'm somewhat stumped that pip on python 2 has such different behaviour from python 3. I'll also try to remove the offending import from the develop-py2 branch in case a future release should still be necessary (hopefully not...).

**Comment by mcmtroffaes** [comment]
This should work now again as 2.3.7-post0 was now yanked. If someone could test the latest python 2 branch, and confirm this also works on legacy Python 2 systems, that would be great:

https://github.com/jazzband/pathlib2/tree/develop-py2

It includes this patch:

https://github.com/jazzband/pathlib2/commit/7eec2dfd574a8e33ab8b621db97facdf23b13e26

**Comment by ghmj2417** [comment]
Doesn't 2.3.7 also have to be yanked?  This, `from _collections_abc import Sequence`, is still in 2.3.7 correct?  I think you also made additional changes from 2.3.6 to 2.3.7 which could break 2.7 installs.

**Comment by mcmtroffaes** [comment]
> Doesn't 2.3.7 also have to be yanked?

It is, no? https://pypi.org/project/pathlib2/#history

**Comment by ghmj2417** [comment]
Yes, it is yanked now.  I was only seeing post0 as yanked.  Weird.  Thank you for taking care of that.  I just tested it and I pulled in 2.3.6 as the latest.

**Comment by mcmtroffaes** [comment]
Awesome, thanks for the quick response. I'll close this, but if someone still can test the develop-py2 branch, that would be much appreciated.

**Comment by maniakjaniak** [comment]
Thank you all so much for replying and looking at this issue. 

How long until pathlib2-2.3.7.post0 is removed? When I rerun the build now it is still using the breaking pathlib2-2.3.7.post0 release.

<img width="1075" alt="Screen Shot 2022-02-10 at 8 24 14 am" src="https://user-images.githubusercontent.com/22334384/153292520-ff420e38-a687-4d15-95f1-1e5accbe0ac3.png">
 
I can see on PyPi the latest version has reverted back to 2.3.6. I'm guessing this is just caching and will resolve sometime today. Thank you again! We're going to try and move our buildkite python over to 3.6 today too.

**Comment by convoliution** [comment]
@mcmtroffaes I'm chiming in here to say I really appreciate your responsiveness on this! I had been investing some time into handling the `six>=1.13` bound since yesterday (personally, I blame `pip`'s lack of a proper dependency resolver until recently), and it's reassuring to see such active maintenance on this project. Thank you, sincerely 🙇🏼

**Comment by convoliution** [comment]
> I'm somewhat stumped that pip on python 2 has such different behaviour from python 3.

This is because the latest and final version of `pip` to support Python 2, `20.3`, [defaults to their legacy dependency resolver for Python 2](https://pip.pypa.io/en/latest/user_guide/#deprecation-timeline) (which simply warns about the version conflict). Python 3 on the other hand has been using the new resolver since Nov 2020, which is more aggressive about updating dependencies already in the environment.

**Comment by alexk307** [comment]
Thanks for the quick turn around @mcmtroffaes! Pretty crazy how fragile these unfrozen dependency chains can quickly blow up in Python 2. This is 100% not your fault, by the way; as the maintainer of the library, you were just publishing a release with improvements. Unfortunately, there's a ton of legacy Python 2 code floating around still being maintained for one reason or another, and with these unbounded dependencies, things can fall apart fast. Thanks again for resolving this.

**Comment by mcmtroffaes** [comment]
> How long until pathlib2-2.3.7.post0 is removed?

I'm not sure, I guess it's just caching indeed. For me it's gone when using pip right now. If really absolutely need be I can make a post1 (subject to someone carefully testing the develop-py2 branch first, just to be on the safe side).

@convoliution Your pointer to pypa is super helpful, I'm thankful to have that explained.

**Comment by ThrawnCA** [comment]
> If really absolutely need be I can make a post1 (subject to someone carefully testing the develop-py2 branch first, just to be on the safe side).

How easy/hard would it be to wrap the `collections_abc` code in a try-except block, so it degrades on older `six` instead of crashing?

**Comment by mcmtroffaes** [comment]
> How easy/hard would it be to wrap the `collections_abc` code in a try-except block, so it degrades on older `six` instead of crashing?

You must have missed the patch I linked above.

**Comment by maniakjaniak** [comment]
I'm still having issues with the import of collections_abc despite the rollback. I don't think this is a caching issue. Sorry, I don't have a lot of experience with library dependencies and what I can do to mitigate the issue with my application on a remote server. We don't use Pathlib2 directly. 

![Screen Shot 2022-02-10 at 10 32 58 am](https://user-images.githubusercontent.com/22334384/153308429-fe2bc5a6-1583-420a-807c-74678fbb5de9.png)

**Comment by convoliution** [comment]
@maniakjaniak You'll need to first uninstall `pathlib2` on your remote server if it's already installed there (as your logs here show `Requirement already satisfied`).

The rollback only prevents new `pip install pathlib2`s from automatically fetching the problematic version.

**Comment by maniakjaniak** [comment]
Thank you @convoliution. These servers are detached and in an autoscale group with AWS so not sure why they wouldn't have a new build each time. I'll find a way :) 

For anyone still watching I did a --force-reinstall and it's still downloading the now-removed version pathlib2-2.3.7.post0. Hopefully this changes in the next day or so.

**Comment by mcmtroffaes** [comment]
Ok, if this keeps being a problem for folks, I'll put together a new release based off the [develop-py2 branch](https://github.com/jazzband/pathlib2/tree/develop-py2), which doesn't rely on a newer six. I have every reason to believe this will be fine this time, however to avoid another mess, I would deeply appreciate confirmation from someone willing to thoroughly test installation and functionality on python 2 before I do another release.

**Comment by maniakjaniak** [comment]
So when I now install virtualenv it is still calling the other, removed, pathlib2 version. (Our buildkite builds are still dead in the water as a result)

I detailed my issue with the maintainers of virtualenv here: https://github.com/pypa/virtualenv/issues/2302 but they said it's not their problem and closed my issue 26 seconds after I opened it. They said it was an issue with your package. 

I know I need to move our BuildKite to python 3 - but is there any chance bumping the version and pushing out a new release would allow the reinstall to use that latest version instead? Is it ridiculous to ask, am I really one of the few people out there still scrabbling in the dirt like a neanderthal with python 2.7... 
Egads. I need coffee. 

Thank you. 

Edit: They have since mentioned I should add my issue to the pip package. I'll try that too.

**Comment by ghmj2417** [comment]
@mcmtroffaes I can test your dev branch today. It will be a couple of hours from now but I can certainly do it to help out.

**Comment by ghmj2417** [comment]
> Ok, if this keeps being a problem for folks, I'll put together a new release based off the [develop-py2 branch](https://github.com/jazzband/pathlib2/tree/develop-py2), which doesn't rely on a newer six. I have every reason to believe this will be fine this time, however to avoid another mess, I would deeply appreciate confirmation from someone willing to thoroughly test installation and functionality on python 2 before I do another release.

I tested your most recent changes in branch `develop-py2` and didn't encounter any issues with using `virtualenv`.  I was using six version 1.9.0 and virtualenv version 20.13.1.  I believe you are safe to release a new version off of develop-py2.

**Comment by mcmtroffaes** [comment]
Thanks for taking this up with upstream @maniakjaniak indeed it looks like a problem somewhere down the pipeline... something is caching the package which breaks the yank.

@ghmj2417 A huge thanks for giving post1 a proper test spin. If anyone else wants to give it a go, it can be installed from pip command line with

```
pip install git+https://github.com/jazzband/pathlib2.git@develop-py2#egg=pathlib2
```

For the record, this passes all regression tests for me. I've also tried the following ones (in independent virtual environments):

```
pip install git+https://github.com/jazzband/pathlib2.git@develop-py2#egg=pathlib2 virtualenv
pip install git+https://github.com/jazzband/pathlib2.git@develop-py2#egg=pathlib2 virtualenv six==1.10.0
```

which worked without warnings/errors. I'll put together a post1 release in a few hours time, unless someone still spots a problem.

**Comment by mcmtroffaes** [comment]
Might as well reopen... 😄

**Comment by mcmtroffaes** [comment]
@maniakjaniak 2.3.7-post1 has just been uploaded to pypi. Are your builds working again?

**Comment by maniakjaniak** [comment]
YES! <3 Thank you, thank you, thank you! We have an epic release going out this weekend (now) and I can't thank you enough. I've never felt so close to vomiting at work for so long.

Python 3 will be the goal post release!

**Comment by mcmtroffaes** [comment]
Great, thanks for confirming @maniakjaniak! I'm very pleased to hear that the issue with buildkite is now resolved.

Thanks everyone for chiming in, and especially @ghmj2417 for the helpful comments and assistance with testing.
